config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'auth/google', as: 'auth'
  get '/auth/google/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get "/profile",    to: "users#show"
  patch "/profile",    to: "users#update"
  get "/profile/edit", to: "users#edit"

  resources :votes, only: [:update], defaults: { format: :json }

  namespace :user, path: ':user', as: :user do
    resources :efforts, except: [:destroy] do
    end
  end

  resources :members, only: [:index]
  resources :volunteers, only: [:index]
  resources :sponsors, only: [:index]
  resources :efforts, only: [:index]
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  def index
  end

end

app/views/volunteers/_edit_form.html.erb
<div class="row">
  <%= form_for @user, url: profile_path(@user) do |f| %>
      <div class="input-field col s6">
        <div class="row">
          <div id="role" class="input-field col s6">
            <p>Select Your Role:</p>
            <%= f.select :role, ['Member','Volunteer','Sponsor'], {} %>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <i class="material-icons prefix">mode_edit</i>
            <%= f.label :hobby, "What are your hobbies?" %>
            <%= f.text_area :hobby, class: "materialize-textarea" %>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <i class="material-icons prefix">mode_edit</i>
            <%= f.label :mission, "What is your mission for Effortful?" %>
            <%= f.text_area :mission, class: "materialize-textarea" %>
          </div>
        </div>
        <div class="row">
          <div id="submit" class="input-field col s6">
            <button class="waves-effect waves-light btn-large" name="action"><%= f.submit "SUBMIT", id: "user-create" %>
              <i class="material-icons left">send</i>
            </button>
          </div>
        </div>
      </div>
      <div class="input-field col s6">
        <h6>Transportation Options</h6>
      </div>
  <% end %>
</div>
<script>
    $(document).ready(function() {
        $('select').material_select();
    });

</script>

app/views/volunteers/_show.html.erb
<div class="row">
  <div class="col s12 m8">
    <div class="card light-blue darken-2 profile-card">
      <div id="member-title" class="card-content white-text">
        <div>
          <%= image_tag(@user.image) %>
          <span><h3><%= @user.name %></h3>
          <h5 id="role-title"><%= @user.role %></h5></span>
          <strong>My Hobbies:</strong> <%= @user.hobby %><br>
          <strong>My Mission:</strong> <%= @user.mission %>
        </div>
      </div>
    </div>
    <div id="s_list" class="col m6">
      <h5>My Members</h5>
      <ul class="collapsible popout" data-collapsible="accordion">
        <% @user.member_count.each do |member_pair| %>
            <li>
              <div class="collapsible-header"><i class="material-icons">stars</i><%= member_pair.first.name %></div>
              <div class="collapsible-body">
                <div id="profile-card" class="card">
                  <div class="card-content row">
                    <div class="s12 l3 col">
                      <%= image_tag(member_pair.first.image) %><div id="chip-color" class="chip"><%= member_pair.last %></div>
                    </div>
                    <div class="s12 l9 col">
                      Mission: <label><%= member_pair.first.mission %></label><br>
                      Hobbies: <label><%= member_pair.first.hobby %></label>
                    </div>
                  </div>
                </div>
              </div>
            </li>
        <% end %>
      </ul>
    </div>
    <div id="v_list" class="col m6">
      <h5>My Sponsors</h5>
      <ul class="collapsible popout" data-collapsible="accordion">
        <% @user.sponsor_count.each do |sponsor_pair| %>
            <li>
              <div class="collapsible-header"><i class="material-icons">person_pin</i><%= sponsor_pair.first.name %></div>
              <div class="collapsible-body">
                <div id="profile-card" class="card">
                  <div class="card-content row">
                    <div class="s12 l3 col">
                      <%= image_tag(sponsor_pair.first.image) %><div id="chip-color" class="chip"><%= sponsor_pair.last %></div>
                    </div>
                    <div class="s12 l9 col">
                      Mission: <label><%= sponsor_pair.first.mission %></label><br>
                      Hobbies: <label><%= sponsor_pair.first.hobby %></label>
                    </div>
                  </div>
                </div>
              </div>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="col s12 m4">
    <div id="my-efforts" class="card white">
      <div id="volunteer-efforts" class="card-content black-text">
        <table>
          <thead>
          <tr>
            <th data-field="id">Active Efforts You Sponsor</th>
            <button id="button-key" class="btn-floating btn-large waves-effect waves-light green"></button> - SUCCESS
            <button id="button-key" class="btn-floating btn-large waves-effect waves-light red"></button> - NEXT TIME
          </tr>
          </thead>
          <tbody>
          <% current_user.efforts.uniq.each do |effort| %>
              <% if effort.schedule && effort.volunteer == current_user %>
                  <tr>
                    <% if effort.schedule.inactive && effort.vote.result == "Success" %>
                        <td><%= link_to effort.title, user_effort_path(id: effort.id, user: effort.member) %><button id="vote-result-button" class="btn-floating btn-large waves-effect waves-light green"></button>
                          <span class="badge">OVER</span></td>
                    <% elsif effort.schedule.inactive %>
                        <td><%= link_to effort.title, user_effort_path(id: effort.id, user: effort.member) %><button id="vote-result-button" class="btn-floating btn-large waves-effect waves-light red"></button>
                          <span class="badge">OVER</span></td>
                    <% elsif effort.schedule.time_remaining < 24 && effort.vote.result == "Success" %>
                        <td><%= link_to effort.title, user_effort_path(id: effort.id, user: effort.member) %><button id="vote-result-button" class="btn-floating btn-large waves-effect waves-light green"></button>
                          <span class="badge"><span class="vote-hrs"><%= effort.schedule.time_remaining %></span> hrs left</span></td>
                    <% elsif effort.schedule.time_remaining < 24 %>
                        <td><%= link_to effort.title, user_effort_path(id: effort.id, user: effort.member) %><button id="vote-result-button" class="btn-floating btn-large waves-effect waves-light red"></button>
                          <span class="badge"><span class="vote-hrs"><%= effort.schedule.time_remaining %></span> hrs left</span></td>
                    <% else %>
                        <td><%= link_to effort.title, user_effort_path(id: effort.id, user: effort.member) %><span class="badge"><span class="hrs"><%= effort.schedule.time_remaining %></span> hrs left</span></td>
                    <% end %>
                  </tr>
              <% end %>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/volunteers/index.html.erb
<div id="volunteer-index" class="row">
  <div class="col s6">
    <div class="card large">
      <div class="card-image waves-effect waves-block waves-light">
        <img class="activator" src="">
      </div>
      <div class="card-content">
        <span class="card-title activator grey-text text-darken-4">Who is an Effortful Volunteer?<i class="material-icons right">more_vert</i></span>
      </div>
      <div class="card-reveal">
        <span class="card-title grey-text text-darken-4">A Volunteer is ...<i class="material-icons right">close</i></span>
        <p>A Volunteer of Effortful is someone that delivers a promise and provides hope, happiness and inspiration for improvement.</p>
      </div>
    </div>
  </div>
  <div class="col s6">
    <h4 class="form-title">Become a Volunteer</h4>
  </div>
</div>