config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'auth/google', as: 'auth'
  get '/auth/google/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get "/profile",    to: "users#show"
  patch "/profile",    to: "users#update"
  get "/profile/edit", to: "users#edit"

  resources :votes, only: [:update], defaults: { format: :json }

  namespace :user, path: ':user', as: :user do
    resources :efforts, except: [:destroy] do
    end
  end

  resources :members, only: [:index]
  resources :volunteers, only: [:index]
  resources :sponsors, only: [:index]
  resources :efforts, only: [:index]
end

app/models/effort.rb
class Effort < ActiveRecord::Base
  # include CacheInvalidator

  has_many :user_efforts
  has_many :users, through: :user_efforts
  has_one :schedule
  has_one :vote

  validates :title, :description, :requested_reward, :length, presence: true

  def member
    User.find(member_id)
  end

  def volunteer
    User.find(volunteer_id) if volunteer_id
  end

  def sponsors
    users.map do |user|
      user if user.role == "Sponsor"
    end.compact
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :user_efforts
  has_many :efforts, through: :user_efforts
  has_many :votes

  validates :first_name, :last_name, :email, presence: true


  def self.find_or_create_from_auth(data)
    user = User.find_or_create_by(provider: data.provider, uid: data.uid)

    user.name =  data.info.name
    user.first_name = data.info.first_name
    user.last_name = data.info.last_name
    user.email = data.info.email
    user.image = data.info.image
    user.token = data.credentials.token

    user.save
    user
  end

  def sponsor_count
    sponsors_with_count = Hash.new{ |k,v| k[v] = 0 }
    self.efforts.uniq.each do |effort|
      effort.sponsors.each do |sponsor|
        sponsors_with_count[sponsor] += 1 if sponsor
      end
    end
    sponsors_with_count
  end

  def volunteer_count
    volunteers_with_count = Hash.new{ |k,v| k[v] = 0 }
    self.efforts.uniq.each do |effort|
        volunteers_with_count[effort.volunteer] += 1 if effort.volunteer
    end
    volunteers_with_count
  end

  def member_count
    members_with_count = Hash.new{ |k,v| k[v] = 0 }
    self.efforts.uniq.each do |effort|
      members_with_count[effort.member] += 1 if effort.member
    end
    members_with_count
  end

  def w3w_split
    location.split('.')
  end


end

app/controllers/efforts_controller.rb
class EffortsController < ApplicationController

  def index
    efforts = Effort.all
    @pending_efforts = efforts.map do |effort|
      effort if effort.schedule.nil?
    end.compact

    @food_efforts = @pending_efforts.map do |effort|
      effort if effort.requested_reward == "Food"
    end.compact

    @clothing_efforts = @pending_efforts.map do |effort|
      effort if effort.requested_reward == "Clothing"
    end.compact

    @job_efforts = @pending_efforts.map do |effort|
      effort if effort.requested_reward == "Job Resources"
    end.compact
  end
end

app/controllers/user/efforts_controller.rb
class User::EffortsController < ApplicationController
  respond_to :json

  before_action :authorize!

  def index
  end

  def show
    @effort = Effort.find(params[:id])
  end

  def new
    @effort = Effort.new
  end

  def create
    @effort = Effort.new(effort_params)
    @effort.update(member_id: current_user.id)
    if @effort.save
      @effort.vote = Vote.new
      current_user.efforts << @effort
      flash[:success] = "#{@effort.title} has been created!"
      redirect_to user_effort_path(id: @effort.id, user: current_user)
    else
      flash[:notice] = "Please select an Effort area"
      render :new
    end

  end

  def edit
    @effort = Effort.find(params[:id])
  end

  def update
    @effort = Effort.find(params[:id])

    if current_volunteer && @effort.sponsors.count == 7
      @effort.update(volunteer_id: current_user.id)
      current_volunteer.efforts << @effort
      @effort.schedule = Schedule.new
      # EffortMailer.send_schedule_over_email(@effort).deliver_now
    elsif current_sponsor && @effort.volunteer && @effort.sponsors.count == 6
      current_sponsor.efforts << @effort
      @effort.schedule = Schedule.new
      # EffortMailer.send_schedule_over_email(@effort).deliver_now
    elsif current_volunteer
      @effort.update(volunteer_id: current_user.id)
      current_volunteer.efforts << @effort
    elsif current_sponsor
      current_sponsor.efforts << @effort
    end

    redirect_to user_effort_path(id: @effort.id, user: @effort.member)

  end

  private

  def effort_params
    params.require(:effort).permit(:title,:description,:requested_reward,:length,:ne_lat,:ne_lng,:sw_lat,:sw_lng)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
    sponsor_count = @user.sponsor_count
    w3w_location = what3words.words_to_position @user.w3w_split
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(user_params)
    if @user.save
      flash[:success] = "Your profile has been updated."
      redirect_to profile_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:mission, :hobby, :location, :role)
  end

end

app/views/user/efforts/_form.html.erb
<div id="effort-form-content" class="row">
  <%= form_for @effort, url: user_efforts_path do |f| %>
      <div class="col s6">
        <h5 id="set-location">Set Location</h5>
        <div id="map-container"><div id="map"></div></div>
      </div>
      <div class="col s6">
        <div class="row">
          <div class="input-field col s12">
          <i class="material-icons prefix">mode_edit</i>
          <%= f.label :title, "Name Your Effort" %>
          <%= f.text_field :title, class: "materialize-textarea" %>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <i class="material-icons prefix">mode_edit</i>
            <%= f.label :description, "What are you going to do?" %>
            <%= f.text_area :description, class: "materialize-textarea" %>
          </div>
        </div>
        <div class="row">
              <div class="input-field col s4">
                <p>Select Your Reward:</p>
                <%= f.select :requested_reward, ['Clothing','Food','Job Resources'], {} %>
              </div>
              <div class="input-field col s4">
                <p>Select Your Effort Length:</p>
                <%= f.select :length, ['1 Day','1 Week'], {} %>
              </div>
              <div class="input-field col s4">
                <button id="effort-submit" class="waves-effect waves-light btn-large" name="action" data-id= <%= @effort.id%> ><%= f.submit "SUBMIT", id: "effort-create" %>
                  <i class="material-icons left">send</i>
                </button>
              </div>
          </div>
          <div class="row">
            <%= f.hidden_field 'ne_lat' %>
            <%= f.hidden_field 'ne_lng' %>
            <%= f.hidden_field 'sw_lat' %>
            <%= f.hidden_field 'sw_lng' %>
          </div>
      </div>
  <% end %>
</div>
  <script async defer src="https://maps.googleapis.com/maps/api/js?signed_in=true&callback=initMap"></script>
  <script>
      $(document).ready(function() {
          $('select').material_select();
      });
  </script>

app/views/user/efforts/_sponsor_schedule.html.erb
<div id="volunteer-schedule" class="row">
  <div class="container">
    <div class="col m12">
      <h3>Effort Delivery Schedule</h3>
      <% if @effort.length == "1 Week" %>
          <table class="highlight">
            <thead>
            <tr>
              <th data-field="name">Sponsor Name</th>
              <th data-field="location">Sponsor Location</th>
              <th data-field="location">Member Location</th>
              <th data-field="day">Pickup Day</th>
            </tr>
            </thead>
            <tbody>
            <% @effort.schedule.donate_schedule.each do |day| %>
                <tr>
                  <td><%= day.last.name %></td>
                  <td><%= day.last.location %></td>
                  <td><%= @effort.member.location %></td>
                  <td><%= day.first.strftime('%a, %d %b %Y') %></td>
                </tr>
            <% end %>
            </tbody>
          </table>
      <% else %>
          <table>
            <thead>
            <tr>
              <th data-field="name">Sponsor Name</th>
              <th data-field="location">Sponsor Location</th>
              <th data-field="location">Member Location</th>
              <th data-field="day">Pickup Day</th>
            </tr>
            </thead>
            <tbody>
            <tr>
              <td><%= @effort.schedule.random_sponsor.name %></td>
              <td><%= @effort.schedule.random_sponsor.location %></td>
              <td><%= @effort.member.location %></td>
              <td><%= @effort.schedule.donate_week[0].strftime('%a, %d %b %Y') %></td>
            </tr>
            </tbody>
          </table>
      <% end %>
    </div>
  </div>
</div>

app/views/user/efforts/_sponsor_vote.html.erb
<div class="row">
  <div class="col m12">
    <div class="row">
      <div class="col m3">
        <div class="vote-card card green">
          <div class="card-content white-text">
            <div class="card-title white-text">
              <span class="card-title">Voting Results</span>
            </div>
            <div id="voting-results">
              <h6>Yes: <span id="yes-result"><%= @effort.vote.yes %></span></h6>
              <h6>No: <span id="no-result"><%= @effort.vote.no %></span></h6>
            </div>
          </div>
        </div>
      </div>
      <% @effort.sponsors.shuffle.each do |sponsor| %>
          <div class="col m3">
            <div class="vote-card card light-blue">
              <div class="card-content white-text">
                <div class="card-title white-text">
                  <%= image_tag(sponsor.image) %>
                  <span class="card-title"><%= sponsor.name %></span>
                </div>
                <p>Time Remaining to Vote: <%= @effort.schedule.time_remaining %> hours</p>
                <% if sponsor == current_user %>
                    <div class="vote-buttons">
                      <% if current_user.votes.include?(@effort.vote) %>
                      <p>You already voted!</p>
                      <% else %>
                      <button id="yes-vote" class="btn-floating btn-large waves-effect waves-light green" data-id=<%= @effort.vote.id%>, user-id=<%= current_user.id%> >YES</button>
                      <button id="no-vote" class="btn-floating btn-large waves-effect waves-light red" data-id=<%= @effort.vote.id %>, user-id=<%= current_user.id%> >NO</button>
                      <% end %>
                    </div>
                <% end %>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>
<script>
  $(document).ready(function(){
    $('#yes-vote').on('click', function(){
      var vote_params    = { vote: { id: $(this).attr("data-id"), type: "yes", user_id: $(this).attr("user-id") } }
      var $votingButtons = $(this).parent();
      debugger;

      $.ajax({
        type:    "PUT",
        url:     "/votes/" + $(this).attr("data-id"),
        data:    vote_params,
        success: function(){
          var votes = parseInt($("#yes-result").html()) + 1;
          $("#yes-result").html(votes);
          $votingButtons.children().remove();
          $votingButtons.prepend("<p>You voted Yes!</p>")
        }
      })
    })

    $('#no-vote').on('click', function(){
      var vote_params = { vote: { id: $(this).attr("data-id"), type: "no", user_id: $(this).attr("user-id") } }
      var $votingButtons = $(this).parent();

      $.ajax({
        type:    "PUT",
        url:     "/votes/" + $(this).attr("data-id"),
        data:    vote_params,
        success: function(){
          var votes = parseInt($("#no-result").html()) + 1;
          $("#no-result").html(votes);
          $votingButtons.children().remove();
          $votingButtons.prepend("<p>You voted No</p>")
        }
      })
    })
  })
</script>

app/views/user/efforts/new.html.erb
<%= render partial: 'user/efforts/form' %>

app/views/user/efforts/show.html.erb
<div class="effort-show row">
  <div class="col m6">
    <div class="card white">
      <div class="card-content">
        <div class="card-title">
          <%= image_tag(@effort.member.image) %>
          <span class="card-title">Effort Information</span>
        </div>
        <h6>Title: <%= @effort.title %></h6>
        <h6>Member: <%= @effort.member.name %></h6>
        <h6>Description: <%= @effort.description %></h6>
        <h6>Length: <%= @effort.length %></h6>
        <div id="show-map-container"><div id="show-map"></div></div>
        <br>
        <br>
      </div>
    </div>
  </div>
  <div class="col m6">
    <div class="card white">
      <div class="card-content">
        <span class="card-title">Sponsors & Volunteer</span>
        <% if current_sponsor && @effort.sponsors.count < 7 %>
            <%= link_to "Add Sponsor", user_effort_path, :method => "put", id: "add-sponsor", class: "btn-floating btn-large waves-effect waves-light red" %>
        <% elsif current_volunteer && @effort.volunteer_id.nil? %>
            <%= link_to "Add Volunteer", user_effort_path, :method => "put", id: "add-sponsor", class: "btn-floating btn-large waves-effect waves-light red" %>
        <% else %>
        <% end %>
        <div class="row">
          <div id="effort-sponsors" class="container">
            <% if @effort.sponsors.count > 0 %>
                <% @effort.sponsors.each do |sponsor|  %>
                    <div class="col m3 s-v">
                      <div id="sponsor"><%= image_tag(sponsor.image) %></div>
                    </div>
                <% end %>
            <% end %>
            <div class="col m3 s-v">
              <div id="volunteer" ><%= image_tag(@effort.volunteer.image) if @effort.volunteer %></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card white">
      <div class="card-content">
        <span class="card-title">Effort Progress</span>
        <% if @effort.schedule %>
          <% if @effort.schedule.inactive %>
            <h6>Start Date: <%= @effort.schedule.start_date %></h6>
            <h6>Result: <%= @effort.vote.result %></h6>
            <% else %>
            <h6>Start Date: <%= @effort.schedule.start_date %></h6>
            <h6>Time Remaining: <%= @effort.schedule.time_remaining %> hours remaining</h6>
            <% end %>
      <% else %>
            <h6>Start Date: TBD</h6>
            <h6>Time Remaining: TBD</h6>
        <% end %>
      </div>
    </div>
    <div class="card white">
      <div class="card-content">
        <span class="card-title">Rewards</span>
        <h6>Type: <%= @effort.member.name %> requested <%= @effort.requested_reward %></h6>
        <h6>Frequency: Once a day</h6>
      </div>
    </div>
  </div>
</div>
<% if @effort.schedule %>
    <% if (current_user == @effort.volunteer || @effort.sponsors.include?(current_user)) && @effort.vote.result == "Success" && @effort.schedule.inactive %>
        <%= render partial: 'sponsor_schedule' %>
    <% elsif @effort.sponsors.include?(current_user) && @effort.schedule.vote_period %>
        <%= render partial: 'sponsor_vote' %>
    <% end %>
<% end %>
<script>
  var showRectangle;
  var showMap;

  function initMap() {

    var effortCenter = {lat: <%= @effort.ne_lat %>, lng: <%= @effort.ne_lng %> }

    showMap = new google.maps.Map(document.getElementById('show-map'), {
      center: effortCenter,
      zoom: 12
    });


    var bounds = {
      north: <%= @effort.ne_lat %>,
      south: <%= @effort.sw_lat %>,
      east: <%= @effort.ne_lng %>,
      west: <%= @effort.sw_lng %>
    };

    // Define the rectangle and set its editable property to true.
    showRectangle = new google.maps.Rectangle({
      strokeColor: '#7F0000',
      strokeOpacity: 0.8,
      strokeWeight: 4,
      fillColor: '#e02032',
      fillOpacity: 0.35,

      bounds: bounds,
      editable: false,
      draggable: false
    });

    showRectangle.setMap(showMap);

  }

</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?signed_in=true&callback=initMap"></script>