config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'auth/google', as: 'auth'
  get '/auth/google/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get "/profile",    to: "users#show"
  patch "/profile",    to: "users#update"
  get "/profile/edit", to: "users#edit"

  resources :votes, only: [:update], defaults: { format: :json }

  namespace :user, path: ':user', as: :user do
    resources :efforts, except: [:destroy] do
    end
  end

  resources :members, only: [:index]
  resources :volunteers, only: [:index]
  resources :sponsors, only: [:index]
  resources :efforts, only: [:index]
end

app/views/layouts/_footer.html.erb
<footer>
  <!-- Modal Structure -->
  <div id="modal1" class="modal bottom-sheet">
    <div class="modal-content">
      <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">X</a>
      <h4 id="footer-header">How Effortful Works</h4>
      <div class="row">
        <div class="col m4">
          <div class="user-info"><i class="material-icons footer-icon">stars</i><h4>Member</h4></div>
          <p>A Member's main task is creating Efforts. An Effort is any action that improves your community. This could be picking up garbage, shoveling snow, helping someone move, or teaching a skill. Whatever you think can improve the community and people around can become an Effort!

            Each Effort will have a location that can be selected on a map and a length of either 1 day or 1 week. A Member can then select a non-monetary reward for completion of an Effort. The Rewards offered are one meal a day, one clothing item a day, or one job resource a day.

            Once an Effort is created, seven Sponsors and one Volunteer can commit to the Effort. Once there are all 8 commitments, the Effort begins.

            If the Member completes the Effort as described, Sponsors will vote to make it a Success.

            A Volunteer will then pick up the Reward from one Sponsor a day and deliver it to the Member.</p>
        </div>
        <div class="col m4">
          <div class="user-info"><i class="material-icons footer-icon">person_pin</i><h4>Sponsor</h4></div>
          <p>A Sponsor is part of the support and reward system of Effortful. As a Sponsor, you can search Effort's around you and pick the ones you would like to support. On an Effort page, simply click the 'Add' button to add yourself as a Sponsor.

            Once there are seven Sponsors and one volunteer added to an Effort, the Effort will begin on the next day. Sponsors are free to check on the Effort progress in the Effort area to determine if the Effort is a success.

            With 24 hours left in an Effort, a Sponsor can vote either 'Yes' or 'No' on the success of the Effort. Each Sponsor gets one vote per Effort. If there is an equal or greater amount of 'Yes' votes, the Effort is deemed a success and the member will receive their Reward.

            A Volunteer will then pick up the Reward from one Sponsor a day and deliver it to the Member. Each successful Effort will have a delivery schedule.</p>
        </div>
        <div class="col m4">
          <div class="user-info"><i class="material-icons footer-icon">shopping_basket</i><h4>Volunteer</h4></div>
          <p>A Volunteer provides the legs and smiles of Effortful. As a Volunteer, you can search Effort's around you and pick the ones you would like to volunteer for. On an Effort page, simply click the 'Add' button to add yourself as a Volunteer.

            Once there are seven Sponsors and one volunteer added to an Effort, the Effort will begin on the next day.

            If the Effort is deemed a success by the Effort Sponsors, a delivery schedule will be created and emailed to the Volunteer to provide a route to the Sponsor then to the Member, once a day. If the Effort length is 1 Day, one of the seven Members will be randomly chosen to provide the Reward.

            A Volunteer will pick up the Reward from the designated location the Sponsor and deliver it to the designated location of the Member. It's as simple as that!</p>
        </div>
      </div>
    </div>
    <div id="footer-login" class="modal-footer">
      <h5>Login now with Google to view your profile and select your role!</h5>
    </div>
  </div>
</footer>
<script>
  $(document).ready(function(){
    // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
    $('.modal-trigger').leanModal();
  });
</script>

app/views/layouts/_navbar.html.erb
<ul id="dropdown2" class="dropdown-content">
  <li><%= link_to "Profile", profile_path %></li>
  <li class="divider"></li>
  <li><%= link_to "Edit", profile_edit_path %></li>
</ul>
<nav>
  <div class="nav-wrapper">
    <%= link_to "Effortful", root_path, class: "brand-logo" %>
    <% if current_user %>
        <ul class="left hide-on-med-and-down">
          <li><%= link_to "Logout", logout_path %></li>
        </ul>
    <% end %>
    <!-- Modal Trigger -->
    <ul class="right hide-on-med-and-down">
      <% if current_user %>
          <li><%= current_user.name %></li>
          <li><a id="profile-button" class="dropdown-button" href="/#" data-activates="dropdown2"><i class="medium material-icons">settings</i></a></li>
          <li><a id="search-button" href="/efforts"><i class="medium material-icons">search</i></a></li>
      <% else %>
          <li><%= link_to "Login", auth_path %></li>
          <li><a id="search-button" href="/efforts"><i class="medium material-icons">search</i></a></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Effortful</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'layouts/navbar' %>
<%= render partial: 'partials/flash_messages' %>
<%= yield %>
<%= render partial: 'layouts/footer' %>
</body>
</html>