config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'auth/google', as: 'auth'
  get '/auth/google/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get "/profile",    to: "users#show"
  patch "/profile",    to: "users#update"
  get "/profile/edit", to: "users#edit"

  resources :votes, only: [:update], defaults: { format: :json }

  namespace :user, path: ':user', as: :user do
    resources :efforts, except: [:destroy] do
    end
  end

  resources :members, only: [:index]
  resources :volunteers, only: [:index]
  resources :sponsors, only: [:index]
  resources :efforts, only: [:index]
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def index
  end

end

app/views/members/_show.html.erb
<div class="row">
  <div class="col s12 m8">
    <div class="card light-blue darken-2 profile-card">
      <div id="member-title" class="card-content white-text">
        <div>
          <%= image_tag(@user.image) %>
          <h3><%= @user.name %></h3>
          <h5 id="role-title"><%= @user.role %></h5>
          <strong>My Hobbies:</strong> <%= @user.hobby %><br>
          <strong>My Mission:</strong> <%= @user.mission %>
        </div>
      </div>
    </div>
    <div id="s_list" class="col m6">
      <h5>My Sponsors</h5>
      <ul class="collapsible popout" data-collapsible="accordion">
        <% @user.sponsor_count.each do |sponsor_pair| %>
            <li>
              <div class="collapsible-header"><i class="material-icons">person_pin</i><%= sponsor_pair.first.name %></div>
              <div class="collapsible-body">
                <div id="profile-card" class="card">
                  <div class="card-content row">
                    <div class="s12 l3 col">
                      <%= image_tag(sponsor_pair.first.image) %><div id="chip-color" class="chip"><%= sponsor_pair.last %></div>
                    </div>
                    <div class="s12 l9 col">
                      Mission: <label><%= sponsor_pair.first.mission %></label><br>
                      Hobbies: <label><%= sponsor_pair.first.hobby %></label>
                    </div>
                  </div>
                </div>
              </div>
            </li>
        <% end %>
      </ul>
    </div>
    <div id="v_list" class="col m6">
      <h5>My Volunteers</h5>
      <ul class="collapsible popout" data-collapsible="accordion">
        <% @user.volunteer_count.each do |volunteer_pair| %>
            <li>
              <div class="collapsible-header"><i class="material-icons">shopping_basket</i><%= volunteer_pair.first.name %></div>
              <div class="collapsible-body">
                <div id="profile-card" class="card">
                  <div class="card-content row">
                    <div class="s12 l3 col">
                      <%= image_tag(volunteer_pair.first.image) %><div id="chip-color" class="chip"><%= volunteer_pair.last %></div>
                    </div>
                    <div class="s12 l9 col">
                      <h6><%= image_tag(volunteer_pair.first.name) %></h6>
                      Mission: <label><%= volunteer_pair.first.mission %></label><br>
                      Hobbies: <label><%= volunteer_pair.first.hobby %></label>
                    </div>
                  </div>
                </div>
              </div>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="col s12 m4">
    <div id="my-efforts" class="card white">
      <div id="volunteer-efforts" class="card-content black-text">
        <table>
          <thead>
          <tr>
            <th data-field="id">Your Active Efforts</th>
            <button id="button-key" class="btn-floating btn-large waves-effect waves-light green"></button> - SUCCESS
            <button id="button-key" class="btn-floating btn-large waves-effect waves-light red"></button> - NEXT TIME
            <th><%= link_to "Create Effort", new_user_effort_path(@user), id: "modal1-button", class: "waves-effect waves-light btn modal-trigger"%></th>
          </tr>
          </thead>
          <tbody>
          <% current_user.efforts.uniq.each do |effort| %>
              <% if effort.schedule && effort.member == current_user %>
                  <tr>
                    <% if effort.schedule.inactive && effort.vote.result == "Success" %>
                        <td><%= link_to effort.title, user_effort_path(id: effort.id, user: effort.member) %><button id="vote-result-button" class="btn-floating btn-large waves-effect waves-light green"></button>
                          <span class="badge">OVER</span></td>
                    <% elsif effort.schedule.inactive %>
                        <td><%= link_to effort.title, user_effort_path(id: effort.id, user: effort.member) %><button id="vote-result-button" class="btn-floating btn-large waves-effect waves-light red"></button>
                          <span class="badge">OVER</span></td>
                    <% elsif effort.schedule.time_remaining < 24 && effort.vote.result == "Success" %>
                        <td><%= link_to effort.title, user_effort_path(id: effort.id, user: effort.member) %><button id="vote-result-button" class="btn-floating btn-large waves-effect waves-light green"></button>
                          <span class="badge"><span class="vote-hrs"><%= effort.schedule.time_remaining %></span> hrs left</span></td>
                    <% elsif effort.schedule.time_remaining < 24 %>
                        <td><%= link_to effort.title, user_effort_path(id: effort.id, user: effort.member) %><button id="vote-result-button" class="btn-floating btn-large waves-effect waves-light red"></button>
                          <span class="badge"><span class="vote-hrs"><%= effort.schedule.time_remaining %></span> hrs left</span></td>
                    <% else %>
                        <td><%= link_to effort.title, user_effort_path(id: effort.id, user: effort.member) %><span class="badge"><span class="hrs"><%= effort.schedule.time_remaining %></span> hrs left</span></td>
                    <% end %>
                  </tr>
              <% end %>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/members/index.html.erb
<div id="member-index" class="row">
  <div class="col s6">
    <div class="card large">
      <div id="member-index-pic" class="card-image waves-effect waves-block waves-light">
      </div>
      <div class="card-content">
        <span class="card-title activator grey-text text-darken-4">Who is an Effortful Member?<i class="material-icons right">more_vert</i></span>
      </div>
      <div class="card-reveal">
        <span class="card-title grey-text text-darken-4">A Member is ...<i class="material-icons right">close</i></span>
        <h6>A Member of Effortful is someone that makes a difference in their community, someone that cares about their future and the health and well-being of themselves and their community.</h6>
      </div>
    </div>
  </div>
  <div class="col s6">
    <h4 class="form-title">How to Be a Member</h4>
    <p>A Member's main task is creating Efforts. An Effort is any action that improves your community. This could be picking up garbage, shoveling snow, helping someone move, or teaching a skill. Whatever you think can improve the community and people around can become an Effort!</p>
    <p>Each Effort will have a location that can be selected on a map and a length of either 1 day or 1 week. A Member can then select a non-monetary reward for completion of an Effort. The Rewards offered are one meal a day, one clothing item a day, or one job resource a day.</p>
    <p>Once an Effort is created, seven Sponsors and one Volunteer can commit to the Effort. Once there are all 8 commitments, the Effort begins.</p>
    <p>If the Member completes the Effort as described, Sponsors will vote to make it a Success.</p>
    <p>A Volunteer will then pick up the Reward from one Sponsor a day and deliver it to the Member.</p>
  </div>
</div>

app/views/members/show.html.erb
<div class="row">
  <div class="col s12 m4">
    <div class="card light-blue">
      <div class="card-content white-text">
        <span class="card-title">About Me</span>
        <p>My Name: John Doe</p>
        <p>My Hobbies: I like reading and nice weather.</p>
      </div>
    </div>
  </div>
  <div class="col s12 m6">
    <div class="card light-blue">
      <div class="card-content white-text">
        <span class="card-title">My Mission</span>
        <p>I am a very simple card. I am good at containing small bits of information.
          I am convenient because I require little markup to use effectively.</p>
      </div>
      <div id="member-efforts" class="card-action">
        <%= render partial: 'partials/effort_card' %>
        <a class="waves-effect waves-light btn modal-trigger" href="#modal2" id="modal2-button">Active Efforts</a>
        <a class="waves-effect waves-light btn modal-trigger" href="#modal3" id="modal3-button">Past Efforts</a>
      </div>
    </div>
  </div>
  <div class="col s12 m2">
    <div class="card light-blue">
      <div class="card-content white-text">
        <span class="card-title">My Sponsors</span>
      </div>
    </div>
  </div>
</div>